/**
 * WebApiAngular.Server | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WeatherForecastTemperatureC } from './weatherForecastTemperatureC';


export interface WeatherForecast { 
    date?: string;
    temperatureC?: WeatherForecastTemperatureC;
    temperatureF?: WeatherForecastTemperatureC;
    summary?: string | null;
}

